[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sdssv-apogee-sf"
version = "0.1.0"
description = "Selection functions for SDSS-V APOGEE surveys"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "astropy",
    "healpy",
]

[project.optional-dependencies]
dev  = ["pytest", "matplotlib"]
docs = ["sphinx", "sphinx-rtd-theme"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sdssv_apogee_sf = ["data/*.npz"]
